version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-kargo-dev
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - GENERIC_TIMEZONE=Europe/Istanbul
      - NODE_ENV=development
      - N8N_LOG_LEVEL=debug
    volumes:
      - n8n_data:/home/node/.n8n
      # Derlenmiş dosyaları mount et (daha güvenilir)
      - ./dist:/home/node/.n8n/custom

volumes:
  n8n_data:
    driver: local