mutation CreatePage($page: PageCreateInput!) {
  pageCreate(page: $page) {
    page {
      id
      title
      handle
      publishedAt
    }
    userErrors {
      code
      field
      message
    }
  }
}