{
    locations(first: 50) {
        nodes {
            id
            isActive
            name
            address {
                address1
                address2
                city
                country
                phone
            }
        }
    }
}
