{
    order(id: "gid://shopify/Order/%s") {
        id
        name
        totalPrice
        currencyCode
        note
        customer {
            email
            displayName
        }
        metafields(first: 100) {
            nodes {
                key
                value
            }
        }
        billingAddress {
            address1
            address2
            city
            firstName
            lastName
            phone
            province
            zip
        }
        shippingAddress {
            address1
            address2
            city
            country
            countryCodeV2
            firstName
            lastName
            phone
            province
            provinceCode
            zip
        }
        returns(first: 20) {
            nodes {
                id
                name
                status
                reverseFulfillmentOrders(first: 20) {
                    nodes {
                        id
                        status
                    }
                }
                returnLineItems(first: 20) {
                    nodes {
                        id
                        quantity
                        customerNote
                        returnReason
                        returnReasonNote
                        ... on ReturnLineItem {
                            fulfillmentLineItem {
                                lineItem {
                                    name
                                    sku
                                    image {
                                        src
                                    }
                                }
                                quantity
                            }
                        }
                    }
                }
            }
        }
    }
}
