mutation reverseDeliveryShippingUpdate($labelInput: ReverseDeliveryLabelInput, $notifyCustomer: Boolean, $reverseDeliveryId: ID!, $trackingInput: ReverseDeliveryTrackingInput) {
  reverseDeliveryShippingUpdate(labelInput: $labelInput, notifyCustomer: $notifyCustomer, reverseDeliveryId: $reverseDeliveryId, trackingInput: $trackingInput) {
    reverseDelivery {
      id
    }
    userErrors {
      field
      message
    }
  }
}