mutation updateOrderMetafields($input: OrderInput!) {
  orderUpdate(input: $input) {
    order {
      id
      metafields(first: 3) {
        edges {
          node {
            id
            namespace
            key
            value
          }
        }
      }
    }
    userErrors {
      message
      field
    }
  }
}